name: Code coverage

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"
      - trigger-coverage-workflow
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "quickwit-*/**"

env:
  QW_S3_ENDPOINT: "http://localstack:4566"
  AWS_DEFAULT_REGION  : "localhost"
  AWS_ACCESS_KEY_ID   : "placeholder"
  AWS_SECRET_ACCESS_KEY: "placeholder"
  TEST_DATABASE_URL: postgres://quickwit-dev:quickwit-dev@localhost:5432/quickwit-metastore-dev

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    # container: public.ecr.aws/l6o9a3f9/quickwit-builder:latest
    container: python:bullseye
    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - "4566:4566"
          - "4571:4571"
          - "8080:8080"
        env:
          SERVICES: s3
        options: >-
          --health-cmd "curl -k https://localhost:4566"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Install awslocal
        run: pip install awscli-local

      - name: Prepare LocalStack S3
        run: ./quickwit-cli/tests/prepare_tests.sh

      - name: Run faulty test
        run: |
          cargo test test_cmd_all_with_s3_localstack_cli --features ci-test

